---
- name: Add required dependencies.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key.
  get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /etc/apt/keyrings/artifacts.elastic.co.asc

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/artifacts.elastic.co.asc] https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
    state: present
    update_cache: true
